steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/market-data-service:latest", "."]
  
  # Push Image to GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/market-data-service:latest"]
  
  # Deploy to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/
      - --image=gcr.io/$PROJECT_ID/market-data-service:latest
      - --location=${_CLUSTER_LOCATION}
      - --cluster=${_CLUSTER_NAME}
      - --namespace=${_NAMESPACE}

substitutions:
  _CLUSTER_LOCATION: us-east1-b
  _CLUSTER_NAME: cluster-1
  _NAMESPACE: default

options:
  logging: CLOUD_LOGGING_ONLY