apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  labels:
    app: market-data-service
spec:
  selector:
    app: market-data-service
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP 